name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Debug (optional)
      - name: Show Project Structure
        run: ls -R

      - name: Build Auth Service
        run: |
          chmod +x auth-service/mvnw
          ./auth-service/mvnw -f auth-service/pom.xml clean install -DskipTests

      - name: Build Email Service
        run: |
          chmod +x email-service/mvnw
          ./email-service/mvnw -f email-service/pom.xml clean install -DskipTests

      - name: Build API Gateway
        run: |
          chmod +x api-gateway/mvnw
          ./api-gateway/mvnw -f api-gateway/pom.xml clean install -DskipTests